name: Terraform Azure Deploy 

on: 
    push:
        branches:
            - vnet
    workflow_dispatch:  
jobs:
    terraform:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache Terraform Plugins
              uses: actions/cache@v2
              with:
                path: ~/.terraform.d/plugin-cache
                key: terraform-plugins-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
                restore-keys: |
                  terraform-plugins-${{ runner.os }}-
                    
            - name: Setup up Terraform 
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.4.5
            - name: Initialize Terraform
              run: terraform init 
        
            - name: Add SSH Public Key
              env:
                SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
                  chmod 600 ~/.ssh/id_rsa.pub
        
            
            - name: Azure Login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Create SSH Directory
              run: mkdir -p ~/.ssh
          
            - name: Terraform Plan 
              run: terraform plan -out=tfplan

            - name: Validate Terraform Code
              run: terraform validate

            - name: Terraform Format
              run: terraform fmt 
              
            - name: Terraform Apply
              if: github.ref == 'refs/heads/vnet'  # Only applies on the main branch
              run: terraform apply -auto-approve tfplan